language: java
script:
- mvn clean install
- mvn test

deploy:
  provider: heroku
  api_key:
    secure: "P/lpvlzcTMT9myel7PjJ9WxG25X6R8SH6ikNvSnC6KbmMyy3yQBh324/1iMEE7qBSjACHsuvS395exP6hEug/NBZ46HYUZ5Snc3XNnQlzrvpMbFIqZS18tt8jt+mWk/60ZqTYhyyCWFE+iNMZdeY+2aEoFgU7F9OOcaqNWMXCLbzS86KpcCIGW0QS6x88g2xuiMogZoiUpFZfsHy/oz6lpFwJsvhxqZgBLu3RTueB/EP5GZ4elEQtoUr5+QiXM5k7yT2w+EVgP6WLIsUSPBvq4p6X5O55pIUH1cn1mSCzwbg04QT23841VB1qK1hSShqYl2y1ARweKONLVvoCeylldJJWyQPYpVzsT1vEiQwn3PyUPV9QSS5Rpr+gD6FwAyrUiHOfDZG+JmybOccxLYTlAzQMWF+hL74a1wzHxTGsVxIly8iaHmxlaIB3Me3wd9daRIngjBm3Rc9JIPebj75Ew6XjkpJRlVtxUj7Gs7b78p0sfZ2WHwJ9JAmM1j2xx1GtD7cYXjIWGct8PCMZEm1/ugw45x4KkaJw2O2KoBqLn+t+kQTOzndYDsl0dOiMOzFCs4ZH60/01UhrkJF2Y5DBzDH8gxggz2PLLzYEtkApkcQOnewndvuolmNA6wExnT37dxL83pWScFdYiG1CtuCihNqSmtMdUWYOhgugrQqIXs="