language: java
script:
- mvn clean install
- mvn test

deploy:
  provider: heroku
  api_key:secure: "k9vJpI3v6/LK59pxySsVM4uY9wCBIuyK6+OpqTeyLI8nSlJBmHPeEy/rnBkx+uWSKUOyBEi0QbeCTThTz+mW0GOo6rCXWzfgxJOEClh115i77FriDrVLjSmUwrzx9zySZmFOjX6GvT9+kvCwJitaMEkGJLyB0dqP/KEjaEe54BcCBrav7uOlR7+FYybri0pBgWa/0VjtmCYM/n+wNKLV7BbpmTpOsHWtsateStPoDI3hGjCafac73gLUA2IHYX6MdBI4OFzCfqFmREjhlJ9uXJ56V3KHsUYkCa+NliFbWMuybtFWOBjnhVISim4EbfsZjbFZBDxCU9MJJPqZL7HNLoc77lM45e9OZrmmNYU4WHb6h4CK2ofyhisplcp2gaSQTG+hW5WFEKERVoTSkanKClPbQcBkDHYxW6Nfa/58evUivUq7q7a9bC44whL4WGVmO3B5GyrB2BMlkW+h3o5iqem4I12TorwvvVizgNvA4QDjSvzt/+J9V9WrMK88tgtpX91dH6YYquWhbX+hBgCt1k+rKjMqwh6CR+KOVV5BhCvN0JJndWL/dXXRUJr7iJDZ5xjgDUm+rhNlQ+JPXSB00MHxI0I8Z2PA6cyPNE6WlRyyspy2XppsoQdLVw9JSinREF6TTIdQkFpJr07yYHnkoneN6LLpOnMlSnYx+SiXkkU="
