language: java
before_script:
- sudo apt-get update -y
- sudo apt-get install rubygems -y
- sudo gem install dpl

script:
- mvn clean install
- mvn test
deploy: &heroku
        provider: heroku
        app: gestiondtareas
        api_key: 7b433b1f-96d8-46a1-9cc9-37a506551f7f