language: java
script:
- mvn clean install
- mvn test

deploy:
  provider: heroku
  api_key:secure: "KLIiOtaEX73xsCbtIBHhRv4ycRWiB1bVnYJj9RMyUD2/WA7PH3XTwKuC/cxVRHLsFu/F1nLQxARjw/MT4bfxs4PIJfY2VnVrUpDcydAwFj7nO9AJ7fIiq+eAq1g2tMtNxmy+mDZVpsa1ioOKlQ9+i+m57c25BTEObx8JXjxMQigC7a6ww5pqHyxszpEJBS8gcrHgfotlr9n7EIMjQ7AsQT0CzvLhWFTBIL0OpXxvgOqwCnw3BM4qzvV7bTkTHUt5UtFpD2pW6wATGHfYboVjlRKt9TpJJtKNsQyzsJA6CQGm2C0OBptgZYvbar91osYDd/H/j+jFx5kZlhqSxX1W8wsDapNkHsl3QfLMfahj+O+DqS6RirO7MTn1s4BphMRGzAKxoDtWjTDv0SlcxDNTUA0ATZ67i0zXD1H7puxsApSsleuz7GZlO7PWh4jpndqnoXFC/llOH7gcMMSFlKbIp2qDYp0KC5UchbM6TnhMzGB5nr18aAuaDFTqLvMmnQiH3rf5uUtcKw5WHdX3qqWNdPhiYtQyiRVTNVtT9fMdixbmTNQM6NcdJDKPmb00AD/uJkbwasJXHZoUZ5B52K9P5nO0uMf4M/NDYvyU8o6/LtvZ1gLJu2s1boAhnGs16HGPteXNYit79RwB9VUDX7NfPbDHxH/IFs/cKddH4CASbLo="