language: java
script:
- mvn clean install
- mvn test

deploy:
  provider: heroku
  api_key:
	secure: "bty+/bQcY5mkXXsfUDwu4C2hUuAZnT3bpKJ9G4vBZYnKeDKKtWIG7jXo2vWtRMzPRscIGyVWW5V4toHwSv4RF9HhYFiAES1kjQWCKhY91bqszzA6pxoxN1p0//cGljRaaiKs3kRBWIWqeZ/+vhcLHwdwyRWgY9nfp7hRp0m2l31qtoG/vCRmPxQHtN0OIcdbAN6lCzzmg6IPxDP8btrAHxe6rKIOkzw9jc4VXjwS3wQx1hwRVcJ7FJJ0709Q7xg0QVyaBXKEV99aoFenctQDv0OEscNwgA9eN+2xQrFchkjFxnM7GVWuDlFHp9mcpZlUttj/RelXz/wow3br1jBiwrGz2/rYCW1wIEoBmLIWQ+Fgn54njw09VEVegV8FqIQGva6aMEOD1Bb4rb/IoHO0QQ8QQL4prhjXo+TTpGpduTLBf2T878wP337dDdPNjFxWeft4DDEkKlx0rIY5jDr+W5gv1g5VFzIgDugP2a0ZJ86xTUyTr6ke/0sZb3qW+VoGc39g8IyBCEj/AB0+EZsFqXWo27Jizbs0malFo8yhkKAXeJQFrui0n3K+QrnKfXxGfRzRn5b7EKlEcO7TPrgLBeYGQY3QJqAOryRYF1FAPPm5ZhBv3cMtAXQcswlAvUtpdA0XHKiY7whAoBQ6PX8hbVOMtNS5IiYF1YplaFUXvac="