language: java
script:
- mvn clean install
- mvn test

deploy:
  provider: heroku
  api_key:
		secure:"TQXGWJ6UGa5sNvgy/jU21CoFWiJlala5mJc2kEyUUGIE1ATwW7rUyEGJBECDAqf1HWoymbj5MnHp7qxJCrT6Jq8Sfd4QjiZ+0VVQ/iHJONmBMMRjA+nCW0870gkqU9RWwQSt/f/sVb7/GnwqewR6cFAMws3J1uC/ER+ZaoSdZGPi4nUQnyZv1T1W/c0ZvcQ/tzXOqsYauZDVi3DX5dEQN7547BUKBg9zCg8wOoaqAEJPtc26hVYoBlK9wzgpuKWuqHwzcMUEGGJYAprurJqIlUBr7maqGdWhPJ5FYhXOAKbDA5cZg04s38sI9TKGpfUtaZwzPN1B+JsoREb1p/hmfvvf36YpZBoGZG5DNJAfE298D6eI/NRVuRNjiY8vXETtyI6T8gRUuHSzB+lAhB6HSl1c80WkZRiDZEyoyiYceNmbzXzjgsvwS/ppG9s/UzzwkRu7Yr5SbTrVy9GUxNXtYnrTXD5TPtMRTEpf2zhgjERt9iBXS/JfBOOawYZ9NeYm82wymKLwa8Z4deBATaL0Iv9BhjWFdV6mHiMx04cu9zSTSQ0iKjXPwITg/r01d+5T/4OlfKQlHhVYfZ7O03sB/G0RvGrO+xdyJr7bKDzutAGeoUw1LKmOEsqRv7d+h1U6ZwTvmBXoCv9Vpz0AAlWDN7KqtHnwTOP9BZIatsKn49k="